#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#include <stdint.h>
#include <stdbool.h>
#include <math.h> // For roundf

// --- Original logical game screen dimensions (DO NOT CHANGE for game logic) ---
#define SCREEN_WIDTH 40
#define SCREEN_HEIGHT 80

// --- New constants for the final display window and scaling ---
#define FINAL_WINDOW_WIDTH 320
#define FINAL_WINDOW_HEIGHT 240
#define GAME_UPSCALE_FACTOR 3

// Calculated dimensions for the scaled game area
#define SCALED_GAME_WIDTH (SCREEN_WIDTH * GAME_UPSCALE_FACTOR)
#define SCALED_GAME_HEIGHT (SCREEN_HEIGHT * GAME_UPSCALE_FACTOR)

// Offsets to center the game area in the final window
#define GAME_AREA_X_OFFSET ((FINAL_WINDOW_WIDTH - SCALED_GAME_WIDTH) / 2)
#define GAME_AREA_Y_OFFSET ((FINAL_WINDOW_HEIGHT - SCALED_GAME_HEIGHT) / 2)

#define WALL_WIDTH 3

#define TESTING_MODE false
#define GOD_MODE (false || TESTING_MODE)
#define DRAW_PARTICLES true

#define DEBUG_DRAW_FPS false

#define PLAYER_WIDTH 5
#define PLAYER_HEIGHT PLAYER_WIDTH

#define GRAVITY 120.0f
#define MAX_SPEED 900.0f
#define MAX_WALL_SLIDE_SPEED (GRAVITY * 0.5f)

#define JUMP_INITIAL_SPEED_Y (TESTING_MODE ? 100.0f : 30.0f)
#define JUMP_INITIAL_SPEED_X 60.0f

#define JUMP_SPEED_CONTINUATION_SPEED_Y (JUMP_INITIAL_SPEED_Y * 2.0f)
#define JUMP_SPEED_CONTINUATION_SPEED_X JUMP_INITIAL_SPEED_X
#define JUMP_CHAIN_BOOST_FACTOR 1.25f

#define SCROLL_MIN_HEIGHT (roundf(SCREEN_HEIGHT * 0.5f))

#define DRAW_PRE_CULL_MARGIN 20

#define KEY_PRESS_BUFFER_TIME 0.2f
#define SCREENSHAKE_AFTER_GAMEOVER_TIME 0.3f
#define JUMP_KEY_TIME_ACCUMULATE 0.2f
#define NUM_JUMPS_FOR_ACCUMULATE 2
#define ACCUM_SPEED_FACTOR 1.3f
#define MAX_GRAB_TIME_FOR_ACCUM_TO_CONTINUE 0.1f
#define TIME_TO_IGNORE_INPUT_AFTER_GAMEOVER 1.0f

// Game States Enum
typedef enum {
    STATE_TITLE_SCREEN = 0, STATE_GAME_OVER, STATE_GRABBING_LEFT, STATE_GRABBING_RIGHT,
    STATE_JUMPING_LEFT_ACTIVE, STATE_JUMPING_LEFT_PASSIVE,
    STATE_JUMPING_RIGHT_ACTIVE, STATE_JUMPING_RIGHT_PASSIVE
} GameState;

// Level Generation Constants
#define LEVEL_GEN_HAZARD_START_HEIGHT SCREEN_HEIGHT
#define LEVEL_GEN_BG_ELEM_START_HEIGHT (SCREEN_HEIGHT / 2)
#define LEVEL_GEN_WALL_ELEM_START_HEIGHT 0
#define LEVEL_GEN_HAZARD_END_HEIGHT (SCREEN_HEIGHT * 30)
#define LEVEL_GEN_HAZARD_START_SEPARATION 100
#define LEVEL_GEN_HAZARD_START_SEPARATION_VARIATION 40
#define LEVEL_GEN_HAZARD_START_SIZE_MIN 2
#define LEVEL_GEN_HAZARD_START_SIZE_MAX 3
#define LEVEL_GEN_HAZARD_END_SEPARATION 50
#define LEVEL_GEN_HAZARD_END_SEPARATION_VARIATION 20
#define LEVEL_GEN_HAZARD_END_SIZE_MIN 4
#define LEVEL_GEN_HAZARD_END_SIZE_MAX 4
#define LEVEL_GEN_BG_ELEM_SEPARATION 100
#define LEVEL_GEN_BG_ELEM_SEPARATION_VARIATION 50
#define LEVEL_GEN_BG_ELEM_PARALLAX_FACTOR 2
#define LEVEL_GEN_WALL_ELEM_HAZARD_BUFFER 5
#define LEVEL_GEN_WALL_ELEM_SEPARATION 30
#define LEVEL_GEN_WALL_ELEM_SEPARATION_VARIATION 10
#define LEVEL_GEN_HAZARDS_END_HEIGHT_MARGIN 100
#define LEVEL_GEN_BG_ELEMS_END_HEIGHT_MARGIN 20
#define LEVEL_GEN_MINIMUM_HEIGHT_INCREASE 20

// MAX Array Sizes
#define MAX_BACKGROUND_ELEMENTS 100
#define MAX_WALL_ELEMENTS 50
#define MAX_HAZARDS 50
#define MAX_PARTICLES 50

#endif // GAME_CONSTANTS_H